### ISSUE TITLE
arm64 arch start zeronet failed

### ISSUE THREAD

**Issue by yeahwong** [SuperSandro2000/docker-images#70]
> ERROR:root:Unhandled exception: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/lib/python3.8/site-packages/gevent/__hub_local.cpython-38-aarch64-linux-gnu.so),
> Traceback (most recent call last):,
>   File "zeronet.py", line 16, in main,
>     import main,
>   File "/app/src/main.py", line 14, in <module>,
>     import gevent,
>   File "/usr/lib/python3.8/site-packages/gevent/__init__.py", line 86, in <module>,
>     from gevent._hub_local import get_hub,
>   File "/usr/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>,
>     import_c_accel(globals(), 'gevent.__hub_local'),
>   File "/usr/lib/python3.8/site-packages/gevent/_util.py", line 105, in import_c_accel,
>     mod = importlib.import_module(cname),
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module,
>     return _bootstrap._gcd_import(name[level:], package, level),
> ImportError: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/lib/python3.8/site-packages/gevent/__hub_local.cpython-38-aarch64-linux-gnu.so)

This is the log, what can i do? Plz help me, thank you.

**Comment by SuperSandro2000** [comment]
The arm64 pre-builts are broken again... I see what I can do.

**Comment by yeahwong** [comment]
So could you fix it?

**Comment by SuperSandro2000** [comment]
It should be fixed now. Please pull the latest image and report back.

**Comment by yeahwong** [comment]
> Unhandled exception: expected str, bytes or os.PathLike object, not NoneType,
> Traceback (most recent call last):,
>   File "zeronet.py", line 16, in main,
>     import main,
>   File "/app/src/main.py", line 74, in <module>,
>     from Plugin import PluginManager,
>   File "/app/src/Plugin/PluginManager.py", line 211, in <module>,
>     plugin_manager = PluginManager()  # Singletone,
>   File "/app/src/Plugin/PluginManager.py", line 19, in __init__,
>     self.path_plugins = os.path.abspath(os.path.dirname(plugins.__file__)),
>   File "/usr/lib/python3.8/posixpath.py", line 152, in dirname,
>     p = os.fspath(p),
> TypeError: expected str, bytes or os.PathLike object, not NoneType,

Thank you, I pulled the latest image, but it still not work.

**Comment by yeahwong** [comment]
The latest image can run, but I used the value of UI_PASSWORD to log in, it can't work.
